// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Laborator_ISP_Stari;

/************************************************************/
/**
 * 
 */
public class AngajatTelefonie {
	/**
	 * 
	 */
	private String nume;

	public AngajatTelefonie(String nume) {
		super();
		this.nume = nume;
	}
};
