// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Laborator_ISP_Stari;

import java.io.*; 
public class MasinaStareSesizareDefectiuneTelefonie {

	private StariSesizari stare;

	/**
	 * 
	 * @param stareDestinatie 
	 * @return 
	 */
	public boolean setStare(StariSesizari stareDestinatie) {
		if (validareTranzitie(stareDestinatie)) {
			stare = stareDestinatie;
			return true;
		}
		else return false;
	}

	/**
	 * 
	 * @param stareDestinatie 
	 * @return 
	 */
	public boolean validareTranzitie(StariSesizari stareDestinatie) {
		if (stare == StariSesizari.Creat && stareDestinatie == StariSesizari.Deschis)
			return true;
		else if (stare == StariSesizari.Deschis && (stareDestinatie == StariSesizari.Amanat || stareDestinatie == StariSesizari.Rezolvat))
			return true;
		else if (stare == StariSesizari.Amanat && stareDestinatie == StariSesizari.Deschis)
			return true;
		else if (stare == StariSesizari.Rezolvat && stareDestinatie == StariSesizari.Inchis)
			return true;
		else return false;
	}

	/**
	 * 
	 * @param numeFisier 
	 */
	public void salvareIstoricStari(String numeFisier) {
		File logFile = new File(numeFisier);
		PrintWriter filePrint;
		try {
			logFile.createNewFile();
		} catch(IOException e1) {
			e1.printStackTrace();
		}
		FileWriter testWriter;
		try {
			testWriter = new FileWriter(logFile);
			filePrint = new PrintWriter(testWriter,true);
			filePrint.println("Stare: " + this.stare);
			
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public MasinaStareSesizareDefectiuneTelefonie() {
		super();
		this.stare = StariSesizari.Creat;
	}
	
};
