// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Laborator_ISP_Stari;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/************************************************************/
/**
 * 
 */
public class SesizareDefectiuneTelefonie {
	/**
	 * 
	 */
	private static int numarSesizare;
	/**
	 * 
	 */
	private long numarTelefon;
	/**
	 * 
	 */
	private TipDefectiuneTelefonie defectiune;
	/**
	 * 
	 */
	private boolean prioritate;
	/**
	 * 
	 */
	public AngajatTelefonie angajattelefonie;
	/**
	 * 
	 */
	public MasinaStareSesizareDefectiuneTelefonie masinastaresesizaredefectiunetelefonie;

	/**
	 * 
	 */
	public void deschidere() {
		this.masinastaresesizaredefectiunetelefonie.setStare(StariSesizari.Deschis);
	}

	/**
	 * 
	 */
	public void inchidere() {
		this.masinastaresesizaredefectiunetelefonie.setStare(StariSesizari.Inchis);
		
	}

	public void amanare() {
		this.masinastaresesizaredefectiunetelefonie.setStare(StariSesizari.Amanat);
	}

	/**
	 * 
	 */
	public void rezolvare() {
		this.masinastaresesizaredefectiunetelefonie.setStare(StariSesizari.Rezolvat);
	}

	/**
	 * 
	 * @param resp 
	 */
	public void alocareResponsabil(AngajatTelefonie resp) {
		this.angajattelefonie=resp;
	}
	
	
	public SesizareDefectiuneTelefonie(long numarTel, TipDefectiuneTelefonie defectiune, boolean prioritate,AngajatTelefonie responsabil) {
		super();
		this.numarTelefon = numarTel;
		this.defectiune = defectiune;
		this.prioritate = prioritate;
		this.angajattelefonie = responsabil;
		masinastaresesizaredefectiunetelefonie = new MasinaStareSesizareDefectiuneTelefonie();
		numarSesizare++;
	}

	
	
};
