// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Laborator_ISP_Stari;

/************************************************************/
/**
 * 
 */
public enum StariSesizari {
	/**
	 * 
	 */
	Creat,
	/**
	 * 
	 */
	Deschis,
	/**
	 * 
	 */
	Amanat,
	/**
	 * 
	 */
	Rezolvat,
	/**
	 * 
	 */
	Inchis;
};
