// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Laborator_ISP_Stari;

/************************************************************/
/**
 * 
 */
public enum TipDefectiuneTelefonie {
	/**
	 * 
	 */
	lipsaTon,
	/**
	 * 
	 */
	apelareImposibila,
	/**
	 * 
	 */
	primireApelImposibila,
	/**
	 * 
	 */
	zgomotFundal;
};
