// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Laborator_ISP_Asociatie;

/************************************************************/
/**
 * 
 */
public class AgentAsigurari {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private AsigurareAuto[] asigurareauto = new AsigurareAuto[20];
	
	private int nrAsigurari = 0;;

	/**
	 * 
	 */
	public void afisareListaAsigurari() {
		
		asigurareauto[0].afisare();
		asigurareauto[1].afisare();
		}
	
	public void addAsigurare(AsigurareAuto a) {
		asigurareauto[nrAsigurari++] = a;
	}
	public String getNume() {
		return nume;
	}
	public void setNume(String nume) {
		this.nume = nume;
	}
	public AsigurareAuto[] getAsigurareauto() {
		return asigurareauto;
	}
	public void setAsigurareauto(AsigurareAuto[] asigurareauto) {
		this.asigurareauto = asigurareauto;
	}
	public int getNrAsigurari() {
		return nrAsigurari;
	}
	public void setNrAsigurari(int nrAsigurari) {
		this.nrAsigurari = nrAsigurari;
	}
};
