// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Laborator_ISP_Asociatie;

/************************************************************/
/**
 * 
 */
public class Client {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String prenume;
	/**
	 * 
	 */
	private long CNP;

	/**
	 * 
	 */
	public void afisare() {
		System.out.println(nume + " " + prenume + " " + CNP);
	}

	public String getNume() {
		return nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public String getPrenume() {
		return prenume;
	}

	public void setPrenume(String prenume) {
		this.prenume = prenume;
	}

	public long getCNP() {
		return CNP;
	}

	public void setCNP(long cNP) {
		CNP = cNP;
	}
};
